### ISSUE TITLE
Segfault upon creation of pubmed footnote

### ISSUE THREAD

**Issue by jonnew** [wagenadl/eln#5] opened 2018-06-24 12:26 UTC
When I attempt to create an automatic pubmed footnote link by pressing <kbd>Ctrl</kbd> + <kbd>N</kbd> near a pubmed ID number, ELN fails with a segmentation fault.  Unfortunately, the exception handling dialog contains an empty backtrace (which might be a meta-issue)

![2018-06-24_546x462_scrot](https://user-images.githubusercontent.com/1429475/41819048-f06fe2a6-7787-11e8-9d1f-bedcdad7fbb7.png)

This happens regardless of whether the number is a valid ID vs a randomly typed long number.

version: cca5af9

**Comment by wagenadl** [comment] 2018-08-01 18:19
Very curious. That doesn't happen for me. Can you run eln from a terminal and send me any debug info that it prints around the time of the crash? Or, better still, compile eln with debugging enabled, run it from gdb, and see if you can reproduce the error with a backtrace?
Thanks!

**Comment by wagenadl** [comment] 2021-04-25 05:08
I still cannot reproduce this issue. Closing it after more than two years.

**Closed as completed by wagenadl** 2021-04-25 05:08 UTC
